### ISSUE TITLE
OSError: Unable to remove Temporary User Data'

### ISSUE THREAD

**Issue by minh230791** [MacKey-255/GoodByeCatpcha#2]
Hello MacKey, I got this problem after solve the recaptcha, both image and audio. How can I solve this problem? I use windows 10.

'2020-01-18 16:09:17,043 1 Result: Success
Traceback (most recent call last):
  File "C:\Users\Admin\Desktop\my project\Selenium\GoodByeCatpcha-master\examples\console.py", line 152, in <module>
    loop.run_until_complete(r.main())
  File "F:\python\lib\asyncio\base_events.py", line 612, in run_until_complete
    return future.result()
  File "C:\Users\Admin\Desktop\my project\Selenium\GoodByeCatpcha-master\examples\console.py", line 135, in main
    result = task.result()
  File "C:\Users\Admin\Desktop\my project\Selenium\GoodByeCatpcha-master\examples\console.py", line 110, in work
    result = await client.start()
  File "F:\python\lib\goodbyecaptcha\solver.py", line 94, in start
    await self.cleanup()
  File "F:\python\lib\goodbyecaptcha\solver.py", line 113, in cleanup
    await self.launcher.killChrome()
  File "F:\python\lib\site-packages\pyppeteer\launcher.py", line 262, in killChrome
    self._cleanup_tmp_user_data_dir()
  File "F:\python\lib\site-packages\pyppeteer\launcher.py", line 154, in _cleanup_tmp_user_data_dir
    raise IOError('Unable to remove Temporary User Data')
OSError: Unable to remove Temporary User Data'

**Comment by mightymercado** [comment]
You can solve this by removing `--no-sandbox` option.

**Comment by MacKey-255** [comment]
> Hello MacKey, I got this problem after solve the recaptcha, both image and audio. How can I solve this problem? I use windows 10.
> 
> '2020-01-18 16:09:17,043 1 Result: Success
> Traceback (most recent call last):
> File "C:\Users\Admin\Desktop\my project\Selenium\GoodByeCatpcha-master\examples\console.py", line 152, in
> loop.run_until_complete(r.main())
> File "F:\python\lib\asyncio\base_events.py", line 612, in run_until_complete
> return future.result()
> File "C:\Users\Admin\Desktop\my project\Selenium\GoodByeCatpcha-master\examples\console.py", line 135, in main
> result = task.result()
> File "C:\Users\Admin\Desktop\my project\Selenium\GoodByeCatpcha-master\examples\console.py", line 110, in work
> result = await client.start()
> File "F:\python\lib\goodbyecaptcha\solver.py", line 94, in start
> await self.cleanup()
> File "F:\python\lib\goodbyecaptcha\solver.py", line 113, in cleanup
> await self.launcher.killChrome()
> File "F:\python\lib\site-packages\pyppeteer\launcher.py", line 262, in killChrome
> self._cleanup_tmp_user_data_dir()
> File "F:\python\lib\site-packages\pyppeteer\launcher.py", line 154, in _cleanup_tmp_user_data_dir
> raise IOError('Unable to remove Temporary User Data')
> OSError: Unable to remove Temporary User Data'
That error is from Chrome when you try to delete the temporary user folder. Review the Pyppetter Repository and you will find the solution. That error is typical when the system you have mounted does not install Chrome properly or does not have the correct privileges. SAlu2s
