### ISSUE TITLE
Why was request interception removed?

### ISSUE THREAD

**Issue by mightymercado** [MacKey-255/GoodByeCatpcha#3]
In Nonocaptcha, captcha javascript and site-key is injected or mocked. It can be configured to generate g-recaptcha-responses without actually visiting the URL. Why was this feature remoed in GoodByeCaptcha?

**Comment by MacKey-255** [comment]
> In Nonocaptcha, captcha javascript and site-key is injected or mocked. It can be configured to generate g-recaptcha-responses without actually visiting the URL. Why was this feature remoed in GoodByeCaptcha?

I did not realize that feature, I will integrate it again as soon as I can. Thanks
