### ISSUE TITLE
i have one question

### ISSUE THREAD

**Issue by azamet90** [MacKey-255/GoodByeCatpcha#8]
does this library works with webdriver library? if yes; is it possible to have some examples to the wiki or here?

**Comment by MacKey-255** [comment]
> does this library works with webdriver library? if yes; is it possible to have some examples to the wiki or here?

No, it only work with pyppeteer chrome browser. Check Pyppeteer Documentation :)
I recommend use this library how micro-service for get captcha-response, send that information in you form via POST and finish it! See: [examples/app.py](https://github.com/MacKey-255/GoodByeCatpcha/blob/master/examples/app.py)
Or you want use [examples/events.py](https://github.com/MacKey-255/GoodByeCatpcha/blob/master/examples/events.py) integration you functionalities with pyppeteer. SAlu2s

**Comment by azamet90** [comment]
thanks for answer
